src/docs/reference/accounts.md
src/docs/reference/functional-accounts.md
src/docs/reference/members.md
src/sidebars.js
src/static/openapi/openapi.yaml

Update the docs to change "Functional Account" to "Account"

PRO-203: Change Functional Account to Account

---

src/sidebars.js

PRO-203: account name

---

src/docusaurus.config.js
src/static/openapi/openapi.yaml

**Why**
- We want documentation to be live at a public URL.
**How**
- Update the base url to be correct for a custom domain.
- Cleanup some documentation.

PRO-195: prepare for production go live

---

src/docs/reference/api-keys.md

**Why**
It is causing builds to fail.

PRO-210: remove broken link

---

src/docs/reference/elements.md

**Why**
There was no mention at all of versions and binaries yet in documentation.
**How**
See files changed.

PRO-317: improve element documentation

---

src/docs/cli/authentication.md
src/docs/reference/api-keys.md
src/docs/reference/authentication-identities.md
src/docs/reference/elements.md

**Why**
It simplifies how we document other things.
**How**
See commit message.

PRO-316: document authentication identities

---

src/package.json
src/yarn.lock

Fixes security vulnerabilities and updates docusarus to latest

PRO-325: Bump dependencies

---

src/static/openapi/openapi.yaml

**Why**
A distribution's next distribution is nullable.
**How**
See changes.

PRO-360: update API spec

---

src/cremini/docs/reference/firmwares.md

We were receiving questions from integrators regarding exactly how it works.
Update the firmware reference with an explanation and an example.

ENG-456: document firmwares ttl

---

LICENSE

Why:
We want to make sure the repository has a valid license

ENG-458: add license

---

src/docs/cli/firmwares/create.md
src/docs/cli/firmwares/delete.md
src/docs/cli/firmwares/get.md
src/docs/cli/firmwares/list.md
src/sidebars.js

Why:
We want to document the firmware CLI command

ENG-467: add firmwares command

---

src/docs/cli/deployments/create.md
src/docs/cli/deployments/delete.md
src/docs/cli/deployments/get.md
src/docs/cli/deployments/list.md
src/docs/cli/deployments/update.md
src/sidebars.js

Why:
We want to document the deployments CLI command

ENG-468: add deployments command

---

src/docs/cli/devices/authenticate.md
src/docs/cli/devices/create.md
src/docs/cli/devices/delete.md
src/docs/cli/devices/get.md
src/docs/cli/devices/list.md
src/docs/cli/devices/update.md
src/sidebars.js

Why:
We want to document the devices CLI command

ENG-470: add devices command

---

src/docs/cli/deployments/create.md
src/docs/cli/deployments/update.md
src/docs/cli/firmwares/create.md

Why:
We want to update our documentation to reflect the changes in our CLI

ENG-467: update CLI documentation

---

src/docs/cli/organization-users/create.md
src/docs/cli/organization-users/delete.md
src/docs/cli/organization-users/get.md
src/docs/cli/organization-users/list.md
src/docs/cli/organization-users/update.md
src/docs/cli/product-users/add.md
src/docs/cli/product-users/delete.md
src/docs/cli/product-users/get.md
src/docs/cli/product-users/list.md
src/docs/cli/product-users/update.md
src/sidebars.js

Why:
We want to add `organization users` and `product users` to our CLI documentation

ENG-487: add commands to support organization and product users

---

src/openapi/peridio-admin-openapi.yaml

Why:
We want to fix inconsistencies in our documentation.
How:
- fix device documentation inconsistencies
- fix firmware documentation inconsistencies
- fix organization user's documentation inconsistencies

ENG-491: fix inconsistencies in our documentation

---

src/docs/cli/ca-certificates/create.md
src/docs/cli/ca-certificates/create_verification_code.md
src/docs/cli/ca-certificates/delete.md
src/docs/cli/ca-certificates/get.md
src/docs/cli/ca-certificates/list.md
src/sidebars.js

Why:
We want to add the documentation for `ca-certificates`

ENG-493: add ca-certificates command

---

src/docs/cli/ca-certificates/create_verification_code.md
src/docs/cli/ca-certificates/delete.md
src/docs/cli/ca-certificates/get.md
src/docs/cli/ca-certificates/list.md
src/docs/cli/ca-certificates/update.md
src/openapi/peridio-admin-openapi.yaml
src/sidebars.js

Why:
We want to update our documentation regarding `ca-certificates`

ENG-489: support verification certs in the API

---

src/docs/guides/creating-firmware.md
src/docs/reference/deployments.md
src/openapi/peridio-device-openapi.yaml

- Fix path in creating firmware guide to be consistent.

ENG-539: document deployment eligibility

---

src/openapi/peridio-admin-openapi.yaml

- Add get, list, create, and update artifacts.
- Add search query language section.

ENG-577: add artifacts

---

src/docusaurus.config.js
src/src/css/custom.css

- Stop left menu in api docs from scrolling out of view.
- Ensure no cells in tables in api docs are missing bottom borders.

ENG-601: fix css bugs

---

src/docs/guides/creating-artifact-versions.md
src/docs/guides/creating-artifacts.md
src/docs/guides/creating-binaries.md
src/docs/guides/creating-bundles.md
src/docs/guides/creating-releases.md
src/docs/guides/release-orchestration.md
src/docs/reference/artifact-versions.md
src/docs/reference/artifacts.md
src/docs/reference/binaries.md
src/docs/reference/bundles.md
src/docs/reference/cohorts.md
src/docs/reference/releases.md
src/docs/reference/update-resolution.md
src/openapi/peridio-admin-openapi.yaml
src/sidebars.js

- Add releases documentation.
- Add bundles documentation.
- Add release orchestration references and guides.

ENG-604: add releases

---

src/docs/cli/devices/create.md
src/docs/cli/devices/update.md
src/docs/guides/creating-devices.md
src/openapi/peridio-admin-openapi.yaml

Note: The Admin API is commented out for now

ENG-946: Device Target Documentation

---

src/.eslintrc.js
src/.prettierrc.json
src/babel.config.js
src/docs/reference/ca-certificates.md
src/docs/reference/just-in-time-provisioning.md
src/docs/reference/verification-certificates.md
src/docs/reference/verification-codes.md
src/docusaurus.config.js
src/sidebars.js
src/src/components/HomepageFeatures.jsx
src/src/components/StackIndex.jsx
src/src/pages/index.jsx

- Add prettier config.
- Add reference "Verification Certificates".
- Add reference "Verification Codes".
- Update "CA Certificate" and "Just in Time Provisioning" references in reaction to other changes.

ENG-990: improve ca cert docs

---

src/docs/cli/deployments/create.md
src/docs/reference/deployments.md
src/openapi/peridio-admin-openapi.yaml

ENG-1034: improve deployment conditions docs

---

src/docusaurus.config.js
src/src/pages/index.jsx
src/src/pages/index.module.css

[ENG-969] - docs: enable search

---

src/docs/reference/binaries.md
src/openapi/peridio-admin-openapi.yaml
src/openapi/peridio-device-openapi.yaml

Fixes ENG-1067: update destroyed binaries reference.

ENG-1065: improve expand docs

---

src/src/pages/index.jsx

fix landing page guides link

---

src/openapi/peridio-admin-openapi.yaml

fixes ENG-1112: relax artifact versions version constraints

ENG-1124: make devices support cohort_prn field

---

src/src/pages/index.jsx

Fixes the broken links for Reference and Guides from when they were moved under platform.

Fix broken links on main page

---

src/docs/integration/linux/reference-designs/qemu-arm64/_category_.json
src/docs/integration/linux/reference-designs/raspberrypi0w/_category_.json
src/docs/integration/linux/reference-designs/raspberrypi3/_category_.json
src/docs/integration/linux/reference-designs/raspberrypi4/_category_.json
src/docs/integration/linux/reference-designs/raspberrypi5/_category_.json

Use category in autogenerated for nice names

---

src/openapi/peridio-admin-openapi.yaml

fixes ENG-1615: expose device prn in API, SDK, CLI, docs

disabled releases

---

src/docs/platform/guides/creating-ca-certificates.md

Reference creating ca certs with Peridio over OpenSSL.

update creating ca certificates guide

---

src/sidebars.js

guides: sidebars

---

src/docs/cli/devices/get-update.md
src/openapi/peridio-admin-openapi.yaml
src/openapi/peridio-device-openapi.yaml

fixes ENG-4123 CLI peridio devices get-update

GET device/{prn}/update

---

src/docs/platform/guides/cloud-delegated-updates.md
src/docs/platform/reference/bundle-distribution.md
src/sidebars.js

- Update the bundle distribution reference.
- Add the cloud delegated updates guide.

update references and add a guide

---

src/docs/platform/getting-started.md

renaming configuration.json to config.json in a few spots

---

src/openapi/peridio-admin-openapi.yaml
src/openapi/peridio-device-openapi.yaml

Fixes ENG-4385, ENG-4418, and ENG-4479.

admin and device api fixes

---

src/docs/cli/artifact-versions/delete.md
src/docs/cli/artifacts/delete.md
src/docs/cli/binaries/delete.md
src/docs/cli/bundles/create.md
src/docs/cli/bundles/delete.md
src/docs/cli/ca-certificates/create.md
src/docs/cli/ca-certificates/update.md
src/docs/cli/deployments/create.md
src/docs/cli/deployments/update.md
src/docs/cli/devices/create.md
src/docs/cli/devices/update.md
src/docs/cli/releases/create.md
src/docs/cli/releases/delete.md
src/docs/cli/releases/update.md
src/docs/cli/tunnels/create.md
src/docs/cli/webhooks/create.md
src/docs/cli/webhooks/update.md
src/openapi/peridio-admin-openapi.yaml

This adds admin http api operations for deletion of:
- binaries
- bundles
- releases
- artifact versions
- artifacts

add admin http api operations for bavarb deletion

---

src/src/pages/index.js
src/src/pages/index.module.css

- Integrated YT video element into hero section layout
- Added loading spinner while video is loading

Ui Update: Added Video Element to Hero Section

---

src/docusaurus.config.js
src/src/components/MegaMenuNavbar/MobileMenu.js
src/src/components/MegaMenuNavbar/index.js
src/src/components/MegaMenuNavbar/styles.css
src/src/css/custom.css

- the `apiKey` changed somewhere (rolled, or inadvertently replaced in an edit) - updated to the correct one
- our custom header was excluding the navbar search component - re-added it to the upper-right
- top of the search modal was getting obscured by header banner - pushed it down a bit
- misc formatting fixes (will be addressed in upcoming ci pr)

fix algolia search

---

src/docs/avocado-linux/introduction.md
src/docs/getting-started/overview.md
src/docs/hardware/supported-hardware.md
src/docs/integration/bundle-management/overview.md
src/docs/integration/certificates/overview.md
src/docs/integration/external-cdn/overview.md
src/docs/integration/guides/peridio-core-custom-integration/android/overview.md
src/docs/integration/guides/peridio-core-custom-integration/introduction.md
src/docs/integration/guides/peridio-core-custom-integration/linux/overview.md
src/docs/integration/guides/peridio-core-custom-integration/linux/reference-designs/imx6ullevk/overview.md
src/docs/integration/guides/peridio-core-custom-integration/linux/reference-designs/khadas-vim3/overview.md
src/docs/integration/guides/peridio-core-custom-integration/linux/reference-designs/qemu-arm64/overview.md
src/docs/integration/guides/peridio-core-custom-integration/linux/reference-designs/raspberrypi0w/overview.md
src/docs/integration/guides/peridio-core-custom-integration/linux/reference-designs/raspberrypi3/overview.md
src/docs/integration/guides/peridio-core-custom-integration/linux/reference-designs/raspberrypi4/overview.md
src/docs/integration/guides/peridio-core-custom-integration/linux/reference-designs/raspberrypi5/overview.md
src/docs/integration/index.md
src/docs/integration/webhooks/overview.md
src/docs/peridio-core/account-management/overview.md
src/docs/peridio-core/device-management/overview.md
src/docs/peridio-core/firmware-management/overview.md
src/docs/peridio-core/introduction.md
src/docs/peridio-core/ota/overview.md
src/docs/platform/reference/overview.md
src/docs/tunnels/overview.md
src/sidebars.js

update overview pages' inner titles
