- src/static/CNAME
**Why**
- The CNAME file is necessary to route DNS correctly across docusaurus deploys.
**How**
- Add CNAME file to static dir.
> PRO-195: add CNAME file

- src/docusaurus.config.js
**Why**
Dark mode has some serious CSS/UI offenses that we simply cannot tolerate in this economy and as such we will hide the switch until a primetime-ready version of dark mode is implemented.
> PRO-225: disable dark mode switch

- src/docs/reference/nerves.md
- src/sidebars.js
Update the reference to discuss steps required to migrate a project
from nerves-hub.org
> PRO-220: Add NervesHub migration docs

- src/docs/reference/node-types.md
- src/sidebars.js
- src/static/openapi/openapi.yaml
Why:
- We want to add specs for node types.
How:
- Add `Node Types` readme.
- Add "Node Types" to sidebar.
- Add `Node Types` to API spec.
- Run formatter on yaml.
> PRO-324: node types specs

- src/docs/reference/api-keys.md
- src/docs/reference/distributions.md
- src/docs/reference/node-groups.md
- src/docs/reference/node-types.md
- src/static/openapi/openapi.yaml
**Why**
Document the integration of nodes, node groups, and distributions.
**How**
- Clarify language in API keys reference.
- Update distributions reference to account for "in-tree"s.
- Update node groups reference to account for node types and
distributions.
- Add node types reference.
- Update OpenAPI spec to callout unique "name" fields:
- Distributions.
- Elements.
- Element versions.
- Nodes.
- Node groups.
- Update API spec to not shorthand element versions and element binaries.
- Functional API changes:
- element_version_binaries.element_version_id.
- nodes.node_type_id.
- node_groups.node_type_id.
- distributions.node_group_id.
- distributions.next_distribution_id.
> PRO-342: update reference and api

- .github/workflows/test-build.yml
Why:
we want to make sure that the docs build correctly
How:
- add git actions workflow files that run `yarn build`
> PRO-218: verify successful build of docs in CI

- src/static/openapi/openapi.yaml
**Why**
The current documentation of errors in the API leaves out some helpful information.
**How**
- Add examples to all error codes.
- Document the "parameter" error code's "reason"s.
> PRO-372: update API spec

- src/static/openapi/openapi.yaml
**Why**
There is an undocumented parameter to an endpoint.
**How**
Document "next_distribution_id" on "update distribution".
> PRO-374: update API spec

- .github/workflows/test-build.yml
- src/.eslintrc.js
- src/package.json
- src/yarn.lock
Why:
We are not enforcing linting or formatting right now, but we should be.
How:
- add docusaurus es-lint plugin for best practices
- add lint command for CI
> PRO-408: enforce eslint --fix-dry-run in CI

- .github/workflows/checks.yml
- README.md
- docs/prerequisites.md
- src/chanterelle/openapi/peridio-api-openapi.yaml
- src/cremini/openapi/peridio-admin-openapi.yaml
- src/cremini/openapi/peridio-device-openapi.yaml
- src/docusaurus.config.js
- src/package.json
- src/redocly.yaml
- src/src/pages/index.jsx
- src/yarn.lock
**Why**
- To automate enforcement of correctness of the specs.
**How**
- Add prerequisites.md to document exact NodeJS version to use.
- Update GitHub workflow to use the exact NodeJS version mentioned in prerequisites.md and to lint OpenAPI specs.
- Link to prerequisites.md in readme.md.
- Fix existing lint issues in OpenAPI specs.
- Add Redocly CLI as a dev dependency to be used to lint OpenAPI specs.
- Add redocly.yaml to configure the Redocly CLI.
- Homogenize API titles on docs homepage.
> PRO-415: lint OpenAPI in CI

- src/cremini-sidebars.js
- src/cremini/docs/reference/ca-certificates.md
- src/cremini/docs/reference/deployments.md
- src/cremini/docs/reference/device-certificates.md
- src/cremini/docs/reference/devices.md
- src/cremini/docs/reference/firmware.md
- src/cremini/docs/reference/just-in-time-registration.md
- src/cremini/docs/reference/keys.md
- src/cremini/docs/reference/organizations.md
- src/cremini/docs/reference/products.md
- src/cremini/docs/reference/users.md
**Why**
- We need to begin to have something in place for the cremini reference so we can gain traction iterating on it.
**How**
- Take a first pass at documenting Cremini resources in the reference.
> PRO-416: add base for cremini reference docs

- src/package.json
- src/yarn.lock
Security and bug fixes.
- Manually bump direct dependencies to latest on npm.
- Yarn install & upgrade.
> ENG-457: update dependencies

- src/package.json
- src/yarn.lock
Yarn audit and GitHub dependabot warn about got, nth-check, and trim.
This isn't actually really an issue according to
https://github.com/facebook/docusaurus/issues/6394, but we will force
usage of newer version anyway to quiet the warnings.
> ENG-457: address package security warnings

- docs/development.md
- src/docs/cli/device-certificates/create.md
- src/docs/cli/device-certificates/delete.md
- src/docs/cli/device-certificates/get.md
- src/docs/cli/device-certificates/list.md
- src/docs/cli/products/create.md
- src/docs/cli/products/delete.md
- src/docs/cli/products/get.md
- src/docs/cli/products/list.md
- src/docs/cli/products/update.md
- src/sidebars.js
Related: ENG-471
Why:
We want to add `device-certificates` and `products` command documentation
How:
- add device-certificates command
- add products command
> ENG-484: add device-certificates command

- src/docs/cli/deployments/create.md
- src/docs/cli/deployments/update.md
- src/docs/cli/products/create.md
- src/docs/cli/products/update.md
- src/openapi/peridio-admin-openapi.yaml
Why:
We want to move delta updates from products to deployments and update our documentation accordingly.
> ENG-516: move delta updates to deployments

- src/openapi/peridio-device-openapi.yaml
Why:
We want to add the quarantined field to the device request me.
> ENG-527: add quarantined status

- src/docs/guides/creating-devices.md
- src/sidebars.js
- src/src/pages/index.jsx
**Why**
- Allow the Peridio web console to not get bogged down by excessive inline documentation.
**How**
- Write the guide.
- Update homepage guides link to land on guides index.
> ENG-545: add device guide

- src/openapi/peridio-admin-openapi.yaml
- Add generic documentation for expanding responses.
- Create experimental section of endpoints and move release orchestration endpoints into it.
- Add operation IDs to all release orchestration endpoints to cleanup their linkable URLs.
- Improve documentation for create, upload, and sign binaries to indicate they are linked and how.
- Document expandable URL field on retrieve Binary.
- Document expandable URL field on get Firmware.
- Add abort Binary upload.
- Add upload Binary.
- Add sign Binary.
- Add size, upload_status, signature, and signing key ID to binary schema.
> ENG-566: update binaries api

- src/openapi/peridio-admin-openapi.yaml
**Why**
So that internal and external beta users can more easily consume and give feedback on relevant documentation.
**How**
Document current release orchestration endpoints and publish them under an experimental section.
> ENG-602: add release orchestration endpoints to public docs (in experimental section)

- src/docs/reference/deployments.md
- src/docs/reference/devices.md
- src/openapi/peridio-admin-openapi.yaml
- src/openapi/peridio-device-openapi.yaml
admin api
- Update monitored headers for device.connected event.
- Update events to have more descriptions for fields and to always say when they are created.
device api
- Update global headers with additional x-peridio legacy headers.
reference
- Deployments: eligibility, failure rates and threshold, and quarantines.
> improve deployment eligibility and headers

- src/.prettierrc.json
- src/docusaurus.config.js
See: https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-gtag
> This plugin is always inactive in development and only active in production to avoid polluting the analytics statistics.
Verified `yarn build` succeeds locally. I also bumped the Prettier `printWidth` to 100 as it seems the config hadn't been formatted in a while, and multiple things wanted to wrap without making it a little more generous.
> add google gtag plugin

- src/docs/integration/linux/reference-designs/raspberrypi0w/overview.md
Updates the target machine name form `raspberrypi0-2w` to `raspberrypi0-2w-64` to match upstream naming
> Raspberry Pi 0-2w: fix target machine name

- src/docs/platform/guides/creating-signing-keys.md
- src/sidebars.js
- Use bash code fences.
- Make it more explicit that the value must be in raw format when submitting to Peridio.
> guides: creating-signing-keys

- src/docs/platform/guides/introduction-to-binary-management.md
- src/docs/platform/guides/introduction-to-bundle-management.md
- src/docs/platform/reference/bundle-distribution.md
- src/docs/platform/reference/bundle-overrides.md
- src/docs/platform/reference/bundles.md
- src/docs/platform/reference/cohorts.md
- src/docs/platform/reference/release-channels.md
- src/docs/platform/reference/releases.md
- src/openapi/peridio-device-openapi.yaml
- src/sidebars.js
- Generally shift language to consider bundle management/distribution to be the higher level topic than releases; releases are a means of performing bundle distribution alongside bundle overrides.
- Add a bundle distribution reference.
- Add a bundle overrides reference.
- Update the bundles reference to support the wider commit's changes and add a section on custom metadata.
- Update cohorts reference to begin introducing release channel language.
- Add a release channels reference.
- Update the releases reference to support the wider commit's changes.
- Update the device API spec to clarify header documentation and link to the relevant reference page.
- Rework the sidebar slightly for clarity and consistency.
- Move firmware and deployments references and guides into deprecated …
> refactor docs for bundle distribution clarity

- src/openapi/peridio-admin-openapi.yaml
Specify that list-artifacts search param can filter name with a case-insensitive substring.
> [AHAPI] fix omission in api spec

- src/schemas/avocado-config.json
This PR updates the avocado-config schema to version `1.1.0`.
This update was automatically generated from the [avocado-config repository](https://github.com/avocado-linux/avocado-config) when tag `1.1.0` was pushed.
- Updated `src/schemas/avocado-config.json` with the latest schema from avocado-config v1.1.0
- Repository: avocado-linux/avocado-config
- Tag: refs/tags/1.1.0
- Commit: 437e43365be7bbc9d49c0e9505e1aa9a1a721e98
> Update avocado-config schema to v1.1.0

- src/src/components/ProvisionGuide/index.tsx
- src/src/data/targetConfigs.ts
- Update ICAM-540 disk space requirement from 8GB to 16GB
- Simplify disk space display formatting in ProvisionGuide component
- Replace screen with tio for serial console connection example
> tweak documentation details
